### ISSUE TITLE
1. Preprocessing

### ISSUE THREAD

**Issue by MScaramuzzi** [MScaramuzzi/A2-Question-Answering-with-Transformers-on-CoQA#3]

**Comment by MScaramuzzi** [comment]
- [x]  remove unanswered questions
- [x] dataset inspection
- [x] train test split

**Comment by bs4bs** [comment]
Uploaded first draft version of Assignment 2 that performs:
task 1 (identify unanswarable to exclude them) and Data inspection
Task 2 generate Training and Validation datasets selecting randomly dialogues with an 80/20 ratio of the dialogues excluding unaswerables. Dataset are split based on stories to ensure that an entire dialogue belongs to the training or validation dataset. 
The script also generates the test dataset.
Please note: for performance reasons, datasets are generated as dictionaries.
Since it was required to create them as pandas dataframes, once created dictionaries are converted in pandas dataframes. Please consider if stricly necessary to have datafarems.
Also note: to avoid rendundand copies of stories, for each dataset 2 dictionaries are created _story contains the stories text and their ID, and _qa, that contains the question / answer pairs, which store also the ID of the corresponding story.
Please note: this is a first draft, please carry out test, since totals do not match exactly the documentation (total dialogues), percentage of UKN do not match and q/a stories/total are high,
Also note: the information stored for the questions and answer should be reviewed once it will be clear the input format to the models.

**Comment by bs4bs** [comment]
.
